app:
  mode: debug
  port: 6666

global_config:
  data_dir: /tmp/upload_temp
  upstream_host: "vskit-video-upload-server"

logger:
  enable_kafka: false
  base:
    log_path: /tmp/log
    log_level: info
    service_name: vskit-video-upload-new-server
  kafka:
    error_topic: "vskit_error_log"
    client:
      worker_pool:
        worker_size: 10
        pool_size: 1024
        timeout: 3
      hosts:
        - 172.31.17.18:9092
        - 172.31.44.173:9092
        - 172.31.63.201:9092